### ISSUE TITLE
Move some ressources to subfolder

### ISSUE THREAD

**Issue by CuzImBisonratte** [sqowey/sqowey#96]
Move the ressources to a subfolder:
- [x] Support-Page
- [x] Changelogs

## Todo:
- [x] Create folder `/misc/`
- [x] Support [Branch 96.1]
    - [x] Copy support page
    - [x] Fix redirectors
- [x] Changelogs [Branch 96.2]
    - [x] Copy changelogs page
    - [x] Fix redirectors
